# Epoch and Learning-Rate variables
num_epochs: 6.0
quantization_epochs: 5.0
init_lr: 0.0001
warmup_lr: 0.00001

training_modifiers:
  - !EpochRangeModifier
    start_epoch: 0.0
    end_epoch: eval(num_epochs)

  - !SetLearningRateModifier
    start_epoch: 0.0
    learning_rate: eval(warmup_lr)   

  - !LearningRateFunctionModifier
    final_lr: 0.0
    init_lr: eval(init_lr)
    lr_func: cosine
    start_epoch: eval(num_epochs-quantization_epochs)
    end_epoch: eval(num_epochs)

quantization_modifiers:
  - !QuantizationModifier
    start_epoch: eval(num_epochs - quantization_epochs)
    ignore: ['classifier', 'AdaptiveAvgPool2d', 'Sigmoid', 'sections.1.0.spatial']
    disable_quantization_observer_epoch: eval(num_epochs - 0.1)
    freeze_bn_stats_epoch: eval(num_epochs - quantization_epochs)
